apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: userDev-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: userDev
    namespace: default
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: userAdmin-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: userAdmin
    namespace: default
roleRef:
  kind: Role
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
